#services:

services:
    app:
        image: sergio:latest
        command: sh -c "yarn install && yarn run dev"
        env_file:
            - .env_app
        ports:
            - '${APPORT}:{$APPORT}'
        depends_on:
            postgres:
                condition: service_healthy

    postgres:
        image: postgres:13.4-alpine3.14
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        env_file:
            - .env
        volumes:
            - type: volume
              source: postgres-sergio-data
              target: /var/lib/postgresql/data
        healthcheck:
            test: pg_isready -U ${PSQL_DB_USERNAME}
            interval: 10s
            timeout: 5s
            retries: 5
        ports:
            - '${PSQL_DB_PORT}:${PSQL_DB_PORT}'
        networks:
            - default-net

volumes:
    postgres-sergio-data:

networks:
    default-net:
#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - 8080:8080
